### ISSUE TITLE
'Apply for membership' workflow hit snag

### ISSUE THREAD

**Issue by awatson1978** [UCSC-MedBook/MedBook-Telescope3#1]
Received the following error in the console when trying to apply for membership to the WCDT collaboration on https://medbook.ucsc.edu

```
Exception in delivering result of invoking 'applyCollaborationMethod': TypeError: Cannot read property 'name' of undefined
    at https://medbook.ucsc.edu/f53a5e9abeff8ef7a4f906f49585ff72607389ad.js:316:5723
    at e.bindEnvironment [as _callback] (https://medbook.ucsc.edu/f53a5e9abeff8ef7a4f906f49585ff72607389ad.js:3:6660)
    at a.extend._maybeInvokeCallback (https://medbook.ucsc.edu/f53a5e9abeff8ef7a4f906f49585ff72607389ad.js:46:11444)
    at a.extend.dataVisible (https://medbook.ucsc.edu/f53a5e9abeff8ef7a4f906f49585ff72607389ad.js:46:11830)
    at https://medbook.ucsc.edu/f53a5e9abeff8ef7a4f906f49585ff72607389ad.js:46:19673
    at Array.forEach (native)
    at Function.A.each.A.forEach (https://medbook.ucsc.edu/f53a5e9abeff8ef7a4f906f49585ff72607389ad.js:1:865)
    at a.extend._runAfterUpdateCallbacks (https://medbook.ucsc.edu/f53a5e9abeff8ef7a4f906f49585ff72607389ad.js:46:19654)
    at a.extend._livedata_data (https://medbook.ucsc.edu/f53a5e9abeff8ef7a4f906f49585ff72607389ad.js:46:19524)
    at e.connection._livedata_data (https://medbook.ucsc.edu/f53a5e9abeff8ef7a4f906f49585ff72607389ad.js:118:5032)
```

**Comment by e-t-k** [comment]
Could not reproduce.
